#!/bin/bash

# Get staged PHP files for PHP CodeSniffer
php_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.php$')
if [ -n "$php_files" ]; then
  echo "Running PHP CodeSniffer on the following files:"
  echo "$php_files"

  echo "$php_files" | xargs vendor/bin/phpcs -d memory_limit=512M --standard=phpcs.xml
  if [ $? -ne 0 ]; then
    echo "PHP CodeSniffer failed. Please fix the errors."
    exit 1
  fi
fi

# Get staged CSS and JS files
css_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(css/.*\.css)$')
js_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(js/.*\.js)$')

# Combine CSS and JS files into a single variable
all_files="$css_files $js_files"

# Run Prettier if there are CSS or JS files
if [ -n "$all_files" ]; then
  echo "Running Prettier on the following files:"
  echo "$all_files"

  echo "$all_files" | xargs npx prettier --write
  if [ $? -ne 0 ]; then
    echo "Prettier failed. Please fix the formatting errors."
    exit 1
  fi

  # Add formatted files back to the staged changes
  echo "$all_files" | xargs git add
fi

echo "All checks passed."
exit 0
