name: Unit tests & PHPCS

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-code-style:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.4', '8.5']
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit --bootstrap __tests__/bootstrap.php __tests__

      - name: Run SDK tests
        run: vendor/bin/phpunit -v -c ./phpunit-sdk-unit.xml

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml --extensions=php --ignore=vendor/ .

  build-and-upload:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: test-and-code-style
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install dependencies and build
        run: |
          composer install
          vendor/bin/phing

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: facebook-pixel-for-wordpress
          path: build/facebook-pixel-for-wordpress-*.zip
